version: '3'
services:
  db:
    image: postgres
    ports:
      - 6432:5432
    environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
    volumes:
      - ./pg/:/var/lib/postgres/data
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    restart: always
#    depends_on:
#      - db

  adminer:
     image: adminer
     #restart: always
     depends_on:
       - db
     ports:
       - 7080:8080

