# Generated by Django 3.2.9 on 2021-11-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("date_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="img",
        ),
    ]
